### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by nguyenthanhvuh** [nguyenthanhvuh/igen#4]
- [ ] (Vu) reread the paper, add more stuff (e.g., applications for iGen). 
- [ ] (Vu) expand writing / discussion for experiments

- [ ] Add interaction length data to paper
- [ ] Add iGen's pure interaction algorithm as front end
- [ ] Optimization to make it scale better
- [ ] Extend experiments to all iGen's benchmarks.   
- [ ] Find more applications (e.g., infinite domains)
